name: Blogger News Poster

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  post-news:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create .env file
      run: |
        echo "BLOG_ID=${{ secrets.BLOG_ID }}" > .env
        
    - name: Create credentials.json
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
        
    - name: Create token.pickle
      run: |
        echo '${{ secrets.TOKEN_PICKLE }}' | base64 -d > token.pickle
        
    - name: Create initial news_log.json if not exists
      run: |
        if [ ! -f news_log.json ]; then
          echo "[]" > news_log.json
        fi
        
    - name: Run Blogger News Poster
      run: python blogger_news_poster.py
      
    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        
        # Check if files exist before adding
        if [ -f news_log.json ]; then
          git add news_log.json
        fi
        
        if [ -f README.md ]; then
          git add README.md
        fi
        
        # Only commit and push if there are changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update news posts [skip ci]"
          git push
        fi